name: json_rpc
version: 0.1.3
author: George Moschovitis <george.moschovitis@gmail.com>
description: JSON-RPC for Dart.
homepage: https://github.com/gmosx/dart-json_rpc
dependencies:
  logging: any
  logging_handlers: any
